name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
        cache: true

    - name: Clean and Get Dependencies
      run: |
        flutter clean
        flutter pub get

    - name: Build Release APK
      run: flutter build apk --release --no-shrink

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: english-chat-app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: error
